### ISSUE TITLE
Question: Use with data binding

### ISSUE THREAD

**Issue by michaelbukachi** [razir/ProgressButton#12]
Hello.
Do I still need to call `bindProgressButton` if I'm using databining? See the snippet below.
```
        val binding = FragmentSignInBinding.bind(view)
        binding.viewModel = viewModel
        binding.lifecycleOwner = this
        binding.signIn.attachTextChangeAnimator()
        binding.signIn.showProgress { ... }
.....
```

**Comment by vermotr** [comment]
Hello, I also would like to use it with data binding. Can we have some help to do this?

**Comment by razir** [comment]
Hi @michaelbukachi ,

Unfortunately, the view doesn't have an access to LifecycleOwner from Data Binding, so you still need to call `bindProgressButton`
