### ISSUE TITLE
defective api for custom view

### ISSUE THREAD

**Issue by beigirad** [razir/ProgressButton#13]
I want to use this library in my custom button that used in whole in my app.
but for [avoiding memory leak](https://github.com/razir/ProgressButton/blob/master/Readme.md#avoiding-memory-leaks), I must use provided `bindProgressButton` extension.
but in custom views we don't have lifecycleOwner! and should implement LifecycleObserver in our custom view and then dispose progressButton resources.

Unfortunately provided api for disposing is defective.

**Comment by razir** [comment]
Hi @beigirad, 
Thank you for the feedback. I understand your problem. It's possible to avoid using LifecycleObserver, but it would make the public API more complicated to use. To maintain the ease of use and to make sure there are no memory leaks you need to pass LifecycleObserver to your custom view
