### ISSUE TITLE
JAVA Usage?

### ISSUE THREAD

**Issue by omkar-tenkale** [razir/ProgressButton#14]
I have imported the library in my android project written in java.
But i couldn't use 
`   bindProgressButton(myButton);`

is it possible to use this library in java?

**Comment by marekx** [comment]
When calling kotlin fun from java you can use:
`com.github.razir.progressbutton.ProgressButtonHolderKt.bindProgressButton(activity, button);`
activity should implement a LifecycleOwner, when using a support library with version 26.1.0 or higher the interface is allready implemented as stated in: https://developer.android.com/topic/libraries/architecture/lifecycle#implementing-lco

**Comment by razir** [comment]
Big thanks to @JcMinarro, you can now find samples  [here](https://github.com/razir/ProgressButton/tree/master/app/src/main/java/com/github/razir/progressexample/java). 
Make sure you update the library version >= 2.1.0
