### ISSUE TITLE
Question: Maven repo

### ISSUE THREAD

**Issue by milosmns** [razir/ProgressButton#2]
Hi, 

I like your library, looks amazing. Is it available in jCenter/MavenCentral or is it only on JitPack? 

Cheers

**Comment by razir** [comment]
Hi, it should be available in jCenter 
http://jcenter.bintray.com/com/github/razir/progressbutton/progressbutton/

**Comment by milosmns** [comment]
Cool, thanks!

**Comment by razir** [comment]
Thanks, I will add it to Readme 👍
