### ISSUE TITLE
How to implement by using Java 

### ISSUE THREAD

**Issue by Rajatagarwal24** [razir/ProgressButton#22]
Hello,

I want to use this lib but unable to understand how can I use it in **layout.xml** file.
And I m using Java for development so can you please help us with how we can implement it with java.
Thanks

**Comment by razir** [comment]
Hi @Rajatagarwal24 ,
for the layout.xml you don't have to do anything special. You can just use general `<Button/>` tag or any of your custom view. This library is not a separate custom view, but just a wrapper around any of the existing views.  
As for the java usage, you check the answer here https://github.com/razir/ProgressButton/issues/14 
Hope it will help. Please let me know if you need a more detailed guide.

**Comment by Rajatagarwal24** [comment]
@razir Thanks for such good lib...
but I had tried your suggestion but not working with java. 
Thanks

**Comment by razir** [comment]
@Rajatagarwal24 could you share the code you have to show the progress?

**Comment by Arielony** [comment]
@razir Please can you upload a Simple Java Implementation? I love this plugin.

**Comment by razir** [comment]
Big thanks to @JcMinarro, you can now find samples  [here](https://github.com/razir/ProgressButton/tree/master/app/src/main/java/com/github/razir/progressexample/java). 
Make sure you update the library version >= 2.1.0
