### ISSUE TITLE
Bintray Shutting Down May 2021 -- Host artifacts elsewhere?

### ISSUE THREAD

**Issue by JvmName** [razir/ProgressButton#31]
Hi! Today JFrog (which owns Bintray/JCenter) announced that they're sunsetting Bintray/JCenter - the last day to access these repositories will be May 2021. https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

I know a lot of tooling goes into artifact upload to a repository, so I wanted to throw a signal flare up now so nobody is caught by surprise on May 1.

**Comment by GuilhE** [comment]
One thing you can do, for now, is to manually sync to MavenCentral (setup OSS [account](https://oss.sonatype.org/#welcome)) through Bintray console. It's a quick fix and latter on you can update the gradle script :)

[This](https://getstream.io/blog/publishing-libraries-to-mavencentral-2021/) may also help.

**Comment by JvmName** [comment]
In case it makes your life any easier, there's a tool that Martin Bonnin developed that seems to make this pretty straightforward: https://github.com/martinbonnin/vespene

**Comment by razir** [comment]
Thanks! I will take care of it

**Comment by GuilhE** [comment]
Another nice helping article: [Migrating old artifacts from JCenter to MavenCentral](https://www.marcogomiero.com/posts/2021/move-libray-jcenter-to-maven/)

**Comment by razir** [comment]
uploaded to mavenCentral https://repo1.maven.org/maven2/com/github/razir/progressbutton/progressbutton/
